#!/usr/bin/env python3
"""Verify that known postcritical defects are generated by block lines."""

from __future__ import annotations
class VerificationError(RuntimeError):
    """Raised when an exact verifier condition fails."""


def require(condition, message):
    if not condition:
        raise VerificationError(str(message))


if not __debug__:
    raise RuntimeError(
        "Verifier refuses optimized execution; rerun without Python -O."
    )



import argparse
import hashlib
import itertools
import json
from collections import Counter, defaultdict
from math import comb
from pathlib import Path

from search_postcritical_interpolation_counterexamples import (
    compositions,
    product_mod,
)


ROOT = Path(__file__).resolve().parent
CERTIFICATE = ROOT / "postcritical_block_line_relation_space.json"


def rref(
    matrix: list[list[int]], prime: int
) -> tuple[list[list[int]], list[int]]:
    data = [[entry % prime for entry in row] for row in matrix]
    rows = len(data)
    columns = len(data[0]) if data else 0
    pivots: list[int] = []
    pivot_row = 0
    for column in range(columns):
        pivot = next(
            (
                row
                for row in range(pivot_row, rows)
                if data[row][column]
            ),
            None,
        )
        if pivot is None:
            continue
        data[pivot_row], data[pivot] = data[pivot], data[pivot_row]
        inverse = pow(data[pivot_row][column], prime - 2, prime)
        data[pivot_row] = [
            inverse * entry % prime for entry in data[pivot_row]
        ]
        for row in range(rows):
            if row == pivot_row:
                continue
            factor = data[row][column]
            if factor:
                data[row] = [
                    (data[row][index] - factor * data[pivot_row][index])
                    % prime
                    for index in range(columns)
                ]
        pivots.append(column)
        pivot_row += 1
        if pivot_row == rows:
            break
    return data, pivots


def rank_mod(matrix: list[list[int]], prime: int) -> int:
    return len(rref(matrix, prime)[1])


def nullspace_basis(
    matrix: list[list[int]], prime: int
) -> list[list[int]]:
    reduced, pivots = rref(matrix, prime)
    columns = len(matrix[0]) if matrix else 0
    pivot_set = set(pivots)
    free_columns = [
        column for column in range(columns) if column not in pivot_set
    ]
    basis = []
    for free in free_columns:
        vector = [0] * columns
        vector[free] = 1
        for row, pivot in enumerate(pivots):
            vector[pivot] = -reduced[row][free] % prime
        basis.append(vector)
    return basis


def transpose(matrix: list[list[int]]) -> list[list[int]]:
    if not matrix:
        return []
    return [list(column) for column in zip(*matrix)]


def locator_values(
    roots: tuple[int, ...],
    sources: tuple[int, ...],
    prime: int,
) -> list[int]:
    return [
        product_mod(((source - root) % prime for root in roots), prime)
        for source in sources
    ]


def line_key(
    prime: int,
    sources: tuple[int, ...],
    block: tuple[int, ...],
) -> tuple[tuple[int, ...], ...]:
    values = locator_values(block, sources, prime)
    inverse_values = [pow(value, prime - 2, prime) for value in values]
    rows = [
        inverse_values,
        [
            source * inverse_value % prime
            for source, inverse_value in zip(sources, inverse_values)
        ],
    ]
    reduced, pivots = rref(rows, prime)
    require(
        len(pivots) == 2,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:120',
    )
    return tuple(tuple(row) for row in reduced[:2])


def evaluation_matrix(
    prime: int,
    sources: tuple[int, ...],
    selected: tuple[int, ...],
) -> tuple[list[tuple[int, ...]], list[list[int]]]:
    a = len(sources)
    degree = len(selected) - a + 2
    monomials = compositions(degree, a)
    labels = list(itertools.combinations(selected, a - 1))
    matrix = []
    for label in labels:
        coordinates = [
            pow(value, prime - 2, prime)
            for value in locator_values(label, sources, prime)
        ]
        scale = pow(coordinates[0], prime - 2, prime)
        coordinates = [
            coordinate * scale % prime for coordinate in coordinates
        ]
        matrix.append(
            [
                product_mod(
                    (
                        pow(coordinate, exponent, prime)
                        for coordinate, exponent in zip(
                            coordinates, exponents
                        )
                    ),
                    prime,
                )
                for exponents in monomials
            ]
        )
    return labels, matrix


def vertex_coordinates(
    prime: int,
    sources: tuple[int, ...],
    label: tuple[int, ...],
) -> list[int]:
    coordinates = [
        pow(value, prime - 2, prime)
        for value in locator_values(label, sources, prime)
    ]
    scale = pow(coordinates[0], prime - 2, prime)
    return [coordinate * scale % prime for coordinate in coordinates]


def rich_line_profile(
    prime: int,
    sources: tuple[int, ...],
    selected: tuple[int, ...],
) -> dict[str, int]:
    labels = list(
        itertools.combinations(selected, len(sources) - 1)
    )
    points = [
        vertex_coordinates(prime, sources, label) for label in labels
    ]
    canonical_keys = {
        line_key(prime, sources, block)
        for block in itertools.combinations(selected, len(sources))
    }
    line_points: dict[
        tuple[tuple[int, ...], ...], set[int]
    ] = defaultdict(set)
    for left, right in itertools.combinations(range(len(points)), 2):
        reduced, pivots = rref(
            [points[left], points[right]], prime
        )
        require(
            len(pivots) == 2,
            'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:195',
        )
        key = tuple(tuple(row) for row in reduced[:2])
        line_points[key].update((left, right))

    rich = {
        key: indices
        for key, indices in line_points.items()
        if len(indices) >= 3
    }
    canonical = [
        len(indices)
        for key, indices in rich.items()
        if key in canonical_keys
    ]
    noncanonical = [
        len(indices)
        for key, indices in rich.items()
        if key not in canonical_keys
    ]
    return {
        "rich_line_count": len(rich),
        "canonical_rich_line_count": len(canonical),
        "noncanonical_rich_line_count": len(noncanonical),
        "maximum_canonical_line_incidence": max(
            canonical, default=2
        ),
        "maximum_noncanonical_line_incidence": max(
            noncanonical, default=2
        ),
    }


def block_line_clusters(
    prime: int,
    sources: tuple[int, ...],
    selected: tuple[int, ...],
) -> list[dict[str, object]]:
    groups: dict[
        tuple[tuple[int, ...], ...], list[tuple[int, ...]]
    ] = defaultdict(list)
    for block in itertools.combinations(selected, len(sources)):
        groups[line_key(prime, sources, block)].append(block)

    clusters = []
    for blocks in groups.values():
        if len(blocks) < 2:
            continue
        root_sets = [set(block) for block in blocks]
        pairwise_disjoint = all(
            root_sets[left].isdisjoint(root_sets[right])
            for left in range(len(root_sets))
            for right in range(left + 1, len(root_sets))
        )
        vertices = sorted(
            {
                tuple(value for value in block if value != omitted)
                for block in blocks
                for omitted in block
            }
        )
        clusters.append(
            {
                "blocks": blocks,
                "vertices": vertices,
                "pairwise_disjoint": pairwise_disjoint,
            }
        )
    return clusters


def relation_accounting(
    prime: int,
    sources: tuple[int, ...],
    selected: tuple[int, ...],
) -> dict[str, object]:
    labels, matrix = evaluation_matrix(prime, sources, selected)
    label_index = {label: index for index, label in enumerate(labels)}
    point_count = len(labels)
    global_defect = point_count - rank_mod(matrix, prime)
    generated: list[list[int]] = []
    cluster_rows = []

    for cluster in block_line_clusters(prime, sources, selected):
        require(
            cluster['pairwise_disjoint'],
            'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:278',
        )
        indices = [label_index[label] for label in cluster["vertices"]]
        local_matrix = [matrix[index] for index in indices]
        local_basis = nullspace_basis(transpose(local_matrix), prime)
        for local_vector in local_basis:
            embedded = [0] * point_count
            for index, value in zip(indices, local_vector):
                embedded[index] = value
            require(
                all((sum((coefficient * entry for coefficient, entry in zip(embedded, column))) % prime == 0 for column in transpose(matrix))),
                'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:286',
            )
            generated.append(embedded)
        cluster_rows.append(
            {
                "block_count": len(cluster["blocks"]),
                "vertex_count": len(indices),
                "local_relation_dimension": len(local_basis),
                "pairwise_disjoint": cluster["pairwise_disjoint"],
            }
        )

    generated_dimension = rank_mod(generated, prime)
    require(
        generated_dimension <= global_defect,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:306',
    )
    return {
        "rank": point_count - global_defect,
        "point_count": point_count,
        "global_relation_dimension": global_defect,
        "block_line_generated_dimension": generated_dimension,
        "non_block_line_quotient_dimension": (
            global_defect - generated_dimension
        ),
        "coincident_line_clusters": cluster_rows,
    }


def characteristic_13_census() -> dict[str, object]:
    prime = 13
    field = set(range(prime))
    signature_counts: Counter[tuple[int, int]] = Counter()
    maximum_cluster_blocks = 0
    maximum_canonical_line_incidence = 0
    maximum_noncanonical_line_incidence = 0
    tested = 0
    for sources in itertools.combinations(range(1, prime), 4):
        selected = tuple(sorted(field - set(sources) - {0}))
        row = relation_accounting(prime, sources, selected)
        signature_counts[
            (
                row["global_relation_dimension"],
                row["block_line_generated_dimension"],
            )
        ] += 1
        maximum_cluster_blocks = max(
            maximum_cluster_blocks,
            max(
                (
                    cluster["block_count"]
                    for cluster in row["coincident_line_clusters"]
                ),
                default=1,
            ),
        )
        require(
            row['non_block_line_quotient_dimension'] == 0,
            'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:346',
        )
        rich_profile = rich_line_profile(prime, sources, selected)
        maximum_canonical_line_incidence = max(
            maximum_canonical_line_incidence,
            rich_profile["maximum_canonical_line_incidence"],
        )
        maximum_noncanonical_line_incidence = max(
            maximum_noncanonical_line_incidence,
            rich_profile["maximum_noncanonical_line_incidence"],
        )
        tested += 1
    return {
        "prime": prime,
        "a": 4,
        "R": 8,
        "tested": tested,
        "relation_signature_counts": {
            f"global_{global_dimension}_block_{block_dimension}": count
            for (global_dimension, block_dimension), count in sorted(
                signature_counts.items()
            )
        },
        "maximum_coincident_block_count": maximum_cluster_blocks,
        "maximum_canonical_line_incidence": (
            maximum_canonical_line_incidence
        ),
        "maximum_noncanonical_line_incidence": (
            maximum_noncanonical_line_incidence
        ),
        "non_block_line_quotient_maximum": 0,
    }


def characteristic_13_noncanonical_threshold_census() -> dict[str, object]:
    prime = 13
    field = set(range(prime))
    rank_counts: Counter[int] = Counter()
    line_signature_counts: Counter[tuple[int, int]] = Counter()
    tested = 0
    for sources in itertools.combinations(range(prime), 4):
        selected = tuple(sorted(field - set(sources)))
        _, matrix = evaluation_matrix(prime, sources, selected)
        rank_counts[rank_mod(matrix, prime)] += 1
        rich = rich_line_profile(prime, sources, selected)
        line_signature_counts[
            (
                rich["maximum_canonical_line_incidence"],
                rich["maximum_noncanonical_line_incidence"],
            )
        ] += 1
        tested += 1
    return {
        "prime": prime,
        "a": 4,
        "R": 9,
        "point_count": comb(9, 3),
        "postcritical_degree": 7,
        "canonical_line_capacity": 8,
        "line_relation_threshold": 9,
        "tested": tested,
        "rank_counts": {
            str(rank): count for rank, count in sorted(rank_counts.items())
        },
        "line_signature_counts": {
            f"canonical_{canonical}_noncanonical_{noncanonical}": count
            for (canonical, noncanonical), count in sorted(
                line_signature_counts.items()
            )
        },
        "maximum_noncanonical_line_incidence": max(
            noncanonical
            for _, noncanonical in line_signature_counts
        ),
        "rank_deficient_configurations": sum(
            count
            for rank, count in rank_counts.items()
            if rank != comb(9, 3)
        ),
    }


def larger_characteristic_examples() -> list[dict[str, object]]:
    cases = [
        (
            17,
            (1, 3, 10, 15),
            (0, 2, 4, 8, 9, 11, 12, 14),
        ),
        (
            19,
            (5, 13, 15, 18),
            (0, 1, 4, 6, 7, 10, 11, 12),
        ),
        (
            23,
            (6, 8, 9, 10),
            (2, 11, 14, 16, 17, 19, 20, 21),
        ),
    ]
    return [
        {
            "prime": prime,
            "sources": list(sources),
            "selected": list(selected),
            **relation_accounting(prime, sources, selected),
        }
        for prime, sources, selected in cases
    ]


def higher_dimensional_planted_examples() -> list[dict[str, object]]:
    cases = [
        {
            "prime": 17,
            "sources": (4, 7, 10, 13, 14),
            "selected": (0, 1, 2, 3, 5, 8, 9, 11, 12, 15),
            "planted_blocks": [
                (0, 2, 3, 5, 11),
                (1, 8, 9, 12, 15),
            ],
        },
        {
            "prime": 17,
            "sources": (1, 5, 8, 15),
            "selected": (
                0,
                2,
                4,
                6,
                7,
                9,
                10,
                11,
                12,
                13,
                14,
                16,
            ),
            "planted_blocks": [
                (2, 4, 10, 13),
                (7, 9, 14, 16),
                (0, 6, 11, 12),
            ],
        },
    ]
    result = []
    for case in cases:
        accounting = relation_accounting(
            case["prime"], case["sources"], case["selected"]
        )
        result.append(
            {
                "prime": case["prime"],
                "a": len(case["sources"]),
                "R": len(case["selected"]),
                "sources": list(case["sources"]),
                "selected": list(case["selected"]),
                "planted_blocks": [
                    list(block) for block in case["planted_blocks"]
                ],
                **accounting,
            }
        )
    return result


def diagonal_cauchy_normal_form_regression() -> dict[str, object]:
    prime = 101
    sources = (0, 1, 2, 3, 4)
    beta = (10, 11, 12, 13, 14)
    scales = (1, 2, 3, 4, 5)
    test_t = (20, 21, 22, 23, 24)
    test_lambda = (30, 31, 32, 33, 34)
    scale_product = product_mod(scales, prime)

    def lagrange_value(index: int, value: int) -> int:
        numerator = product_mod(
            (
                (value - source) % prime
                for position, source in enumerate(sources)
                if position != index
            ),
            prime,
        )
        denominator = product_mod(
            (
                (sources[index] - source) % prime
                for position, source in enumerate(sources)
                if position != index
            ),
            prime,
        )
        return numerator * pow(denominator, prime - 2, prime) % prime

    def direct_value(t_value: int, lambda_value: int) -> int:
        return sum(
            lagrange_value(index, t_value)
            * product_mod(
                (
                    scales[position]
                    * (lambda_value - beta[position])
                    for position in range(len(sources))
                    if position != index
                ),
                prime,
            )
            for index in range(len(sources))
        ) % prime

    def cauchy_value(t_value: int, lambda_value: int) -> int:
        source_product = product_mod(
            ((t_value - source) for source in sources), prime
        )
        beta_product = product_mod(
            ((lambda_value - root) for root in beta), prime
        )
        diagonal_sum = 0
        for index, source in enumerate(sources):
            source_derivative = product_mod(
                (
                    (source - other) % prime
                    for position, other in enumerate(sources)
                    if position != index
                ),
                prime,
            )
            weight = (
                scale_product
                * pow(scales[index], prime - 2, prime)
                * pow(source_derivative, prime - 2, prime)
            ) % prime
            denominator = (
                (t_value - source)
                * (lambda_value - beta[index])
            ) % prime
            diagonal_sum += weight * pow(denominator, prime - 2, prime)
        return source_product * beta_product * diagonal_sum % prime

    matrix = [
        [direct_value(t_value, lambda_value) for lambda_value in test_lambda]
        for t_value in test_t
    ]
    checked_pairs = 0
    for t_value in test_t:
        for lambda_value in test_lambda:
            require(
                direct_value(t_value, lambda_value) == cauchy_value(t_value, lambda_value),
                'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:591',
            )
            checked_pairs += 1
    return {
        "prime": prime,
        "a": len(sources),
        "checked_pairs": checked_pairs,
        "evaluation_matrix_rank": rank_mod(matrix, prime),
        "expected_full_rank": len(sources),
    }


def koalabear_block_line_table() -> list[dict[str, int | bool]]:
    rows = []
    for a in range(12, 17):
        for regular_count in range(53 + a, 70):
            degree = regular_count - a + 2
            maximum_blocks = regular_count // a
            remainder = regular_count % a
            near_full_allowance = int(remainder == a - 1)
            maximum_vertices = (
                a * maximum_blocks + near_full_allowance
            )
            overload_threshold = degree + 2
            conic_circuit_support = 2 * degree + 2
            cubic_circuit_support = 3 * degree
            minimum_support_deficit = (a - 4) * (a - 1)
            rows.append(
                {
                    "a": a,
                    "R": regular_count,
                    "postcritical_degree": degree,
                    "maximum_disjoint_blocks": maximum_blocks,
                    "near_full_fiber_allowance": near_full_allowance,
                    "maximum_canonical_line_vertices": maximum_vertices,
                    "overload_threshold": overload_threshold,
                    "low_support_line_cutoff": 2 * degree + 1,
                    "block_line_overload_possible": (
                        maximum_vertices >= overload_threshold
                    ),
                    "maximum_forced_relation_dimension": max(
                        0, maximum_vertices - (degree + 1)
                    ),
                    "minimum_support_no_common_root_deficit": (
                        minimum_support_deficit
                    ),
                    "minimum_roots_of_multiplicity_at_least_a_minus_2": max(
                        0,
                        regular_count
                        - minimum_support_deficit // 2,
                    ),
                    "minimum_overload_grs_length": overload_threshold,
                    "minimum_overload_grs_dimension": a,
                    "minimum_overload_grs_distance": (
                        overload_threshold - a + 1
                    ),
                    "minimum_overload_grs_total_weight_excess": (
                        minimum_support_deficit
                    ),
                    "conic_circuit_support": conic_circuit_support,
                    "reducible_conic_component_load": degree + 1,
                    "both_reducible_conic_components_can_be_canonical": (
                        maximum_vertices >= degree + 1
                    ),
                    "cubic_complete_intersection_support": (
                        cubic_circuit_support
                    ),
                    "first_unclassified_circuit_support": (
                        cubic_circuit_support + 1
                    ),
                }
            )
    return rows


def payload() -> dict[str, object]:
    result = {
        "status": (
            "KNOWN_POSTCRITICAL_RELATIONS_BLOCK_LINE_GENERATED_"
            "NON_BLOCK_LINE_CLASSIFICATION_OPEN"
        ),
        "characteristic_13_relation_space_census": (
            characteristic_13_census()
        ),
        "characteristic_13_noncanonical_threshold_census": (
            characteristic_13_noncanonical_threshold_census()
        ),
        "larger_characteristic_examples": (
            larger_characteristic_examples()
        ),
        "higher_dimensional_planted_examples": (
            higher_dimensional_planted_examples()
        ),
        "diagonal_cauchy_normal_form_regression": (
            diagonal_cauchy_normal_form_regression()
        ),
        "rich_line_guardrails": [
            {
                "prime": prime,
                "a": len(sources),
                "R": len(selected),
                **rich_line_profile(prime, sources, selected),
            }
            for prime, sources, selected in [
                (
                    13,
                    (0, 1, 2, 5),
                    (3, 4, 6, 7, 8, 9, 11, 12),
                ),
                (
                    17,
                    (4, 7, 10, 13, 14),
                    (0, 1, 2, 3, 5, 8, 9, 11, 12, 15),
                ),
            ]
        ],
        "koalabear_block_line_capacity": koalabear_block_line_table(),
        "claims": {
            "coincident_distinct_blocks_are_pairwise_disjoint": "PROVED",
            "known_relation_spaces_are_block_line_generated": "PROVED",
            "a12_R69_block_line_overload": "IMPOSSIBLE",
            "non_block_line_relation_classification": "OPEN",
            "same_record_payment": "OPEN",
            "cap_68": "OPEN",
        },
    }
    canonical = json.dumps(
        result, sort_keys=True, separators=(",", ":")
    ).encode()
    result["payload_sha256"] = hashlib.sha256(canonical).hexdigest()
    return result


def validate(data: dict[str, object]) -> None:
    census = data["characteristic_13_relation_space_census"]
    require(
        census['tested'] == 495,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:727',
    )
    require(
        census['relation_signature_counts'] == {'global_0_block_0': 474, 'global_1_block_1': 18, 'global_2_block_2': 3},
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:728',
    )
    require(
        census['non_block_line_quotient_maximum'] == 0,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:733',
    )
    require(
        census['maximum_coincident_block_count'] == 2,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:734',
    )
    require(
        census['maximum_canonical_line_incidence'] == 8,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:735',
    )
    require(
        census['maximum_noncanonical_line_incidence'] == 4,
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:736',
    )

    threshold = data["characteristic_13_noncanonical_threshold_census"]
    require(
        threshold == {'prime': 13, 'a': 4, 'R': 9, 'point_count': 84, 'postcritical_degree': 7, 'canonical_line_capacity': 8, 'line_relation_threshold': 9, 'tested': 715, 'rank_counts': {'84': 715}, 'line_signature_counts': {'canonical_5_noncanonical_4': 442, 'canonical_8_noncanonical_4': 195, 'canonical_8_noncanonical_5': 78}, 'maximum_noncanonical_line_incidence': 5, 'rank_deficient_configurations': 0},
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:739',
    )

    larger = data["larger_characteristic_examples"]
    require(
        [row['prime'] for row in larger] == [17, 19, 23],
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:759',
    )
    require(
        all((row['global_relation_dimension'] == 1 and row['block_line_generated_dimension'] == 1 and (row['non_block_line_quotient_dimension'] == 0) for row in larger)),
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:760',
    )

    planted = data["higher_dimensional_planted_examples"]
    require(
        [(row['a'], row['R']) for row in planted] == [(5, 10), (4, 12)],
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:768',
    )
    require(
        [(row['global_relation_dimension'], row['block_line_generated_dimension'], row['non_block_line_quotient_dimension']) for row in planted] == [(2, 2, 0), (1, 1, 0)],
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:772',
    )

    require(
        data['diagonal_cauchy_normal_form_regression'] == {'prime': 101, 'a': 5, 'checked_pairs': 25, 'evaluation_matrix_rank': 5, 'expected_full_rank': 5},
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:781',
    )

    guardrails = data["rich_line_guardrails"]
    require(
        [(row['a'], row['R']) for row in guardrails] == [(4, 8), (5, 10)],
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:790',
    )
    require(
        [(row['maximum_canonical_line_incidence'], row['maximum_noncanonical_line_incidence']) for row in guardrails] == [(8, 3), (10, 3)],
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:794',
    )

    rows = data["koalabear_block_line_capacity"]
    require(
        len(rows) == sum((70 - (53 + a) for a in range(12, 17))),
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:803',
    )
    hardest = next(
        row for row in rows if row["a"] == 12 and row["R"] == 69
    )
    require(
        hardest == {'a': 12, 'R': 69, 'postcritical_degree': 59, 'maximum_disjoint_blocks': 5, 'near_full_fiber_allowance': 0, 'maximum_canonical_line_vertices': 60, 'overload_threshold': 61, 'low_support_line_cutoff': 119, 'block_line_overload_possible': False, 'maximum_forced_relation_dimension': 0, 'minimum_support_no_common_root_deficit': 88, 'minimum_roots_of_multiplicity_at_least_a_minus_2': 25, 'minimum_overload_grs_length': 61, 'minimum_overload_grs_dimension': 12, 'minimum_overload_grs_distance': 50, 'minimum_overload_grs_total_weight_excess': 88, 'conic_circuit_support': 120, 'reducible_conic_component_load': 60, 'both_reducible_conic_components_can_be_canonical': True, 'cubic_complete_intersection_support': 177, 'first_unclassified_circuit_support': 178},
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:807',
    )

    a14 = {
        row["R"]: row
        for row in rows
        if row["a"] == 14
    }
    require(
        {regular_count: (row['reducible_conic_component_load'], row['maximum_canonical_line_vertices'], row['both_reducible_conic_components_can_be_canonical']) for regular_count, row in a14.items()} == {67: (56, 56, True), 68: (57, 56, False), 69: (58, 57, False)},
        'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:836',
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--tamper-selftest", action="store_true")
    args = parser.parse_args()

    data = payload()
    validate(data)
    if args.emit:
        CERTIFICATE.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n"
        )
    if args.check:
        require(
            json.loads(CERTIFICATE.read_text()) == data,
            'verification condition failed at experimental/notes/frontier-adjacent/kb_mca_v4_equality_wall_geometry_v1/verification/verify_postcritical_block_line_relation_space.py:864',
        )
    if args.tamper_selftest:
        tampered = json.loads(json.dumps(data))
        hardest = next(
            row
            for row in tampered["koalabear_block_line_capacity"]
            if row["a"] == 12 and row["R"] == 69
        )
        hardest["block_line_overload_possible"] = True
        try:
            validate(tampered)
        except VerificationError:
            pass
        else:
            raise VerificationError("tamper was not rejected")

    print("characteristic-13 relation quotient census: PASS")
    print("cross-characteristic relation generation: PASS")
    print("KoalaBear block-line capacity: PASS")
    print("diagonal Cauchy normal form: PASS")
    print("Cayley-Bacharach circuit arithmetic: PASS")
    print(f"payload_sha256={data['payload_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
