#!/usr/bin/env python3
"""L1 prefix-fiber divisor-coefficient scanner and quotient-periodic separator.

This is an EXPERIMENTAL / AUDIT scanner for the L1 program in `agents.md`.  It
does not assert Reed--Solomon list decoding, MCA, or protocol safety, and it
does not upgrade any theorem status.

Object.  Let ``H <= F_q^*`` be the multiplicative subgroup of order ``n`` (here
``n | q - 1`` so ``H = mu_n`` splits completely over ``F_q``).  For a prefix
length ``sigma`` and complement size ``m = n - (k + sigma)``, the monomial-prefix
fiber of Paper B (`slackMCA_v3.tex`, `prop:monomial-fiber`,
`conj:prefix-local`) is computed here in its *complement-locator* form, using the
bijection recorded in `experimental/l1_aperiodic_prefix_collision.md`:

    Phi_sigma^{-1}(c)  <->  { monic degree-m divisors D of X^n - 1 over F_q
                             whose top sigma coefficients are prescribed }.

A monic degree-``m`` divisor of ``X^n - 1`` is exactly the locator
``L_A(X) = prod_{a in A}(X - a)`` of an ``m``-subset ``A <= H`` (the complement
of the agreement support).  Two supports share a prefix fiber iff their
complement locators share their top ``sigma`` coefficients.  So the prefix-fiber
histogram is the histogram of ``m``-subsets of ``H`` bucketed by the top
``sigma`` coefficients of their locator.

Quotient-periodic separation.  For a subgroup ``K_d <= H`` of order ``d`` a
``K_d``-coset-union divisor (root set closed under multiplication by ``K_d``) has
locator equal to a polynomial in ``X^d``; such divisors inject into the
degree-``m/d`` divisors of ``Y^{n/d} - 1`` via ``Y = X^d``.  These are the
"quotient-core" contributions ``Quot_{sigma,c}`` of `conj:prefix-local`, active
when ``d > sigma``.  The scanner counts them and certifies the aperiodic
remainder.

Output: JSON plus a human-readable table.  Standard library only.
"""

import argparse
import itertools
import json
import sys
from collections import defaultdict
from math import comb, gcd


# ---------------------------------------------------------------------------
# Prime-field helpers (standard library only).
# ---------------------------------------------------------------------------
def factorize(num):
    """Return the set of prime factors of ``num``."""
    factors = set()
    d = 2
    while d * d <= num:
        while num % d == 0:
            factors.add(d)
            num //= d
        d += 1
    if num > 1:
        factors.add(num)
    return factors


def primitive_root(p):
    """Smallest primitive root of the prime field F_p."""
    if p == 2:
        return 1
    phi = p - 1
    primes = factorize(phi)
    for g in range(2, p):
        if all(pow(g, phi // q, p) != 1 for q in primes):
            return g
    raise ValueError(f"no primitive root found for p={p}")


def subgroup(p, n):
    """The order-``n`` multiplicative subgroup of F_p^*, as a list.

    Requires ``n | p - 1``.  Returns the subgroup generated by ``g^((p-1)/n)``
    where ``g`` is a primitive root, with element ``0`` first (the identity).
    """
    if (p - 1) % n != 0:
        raise ValueError(f"n={n} does not divide p-1={p-1}")
    g = primitive_root(p)
    h = pow(g, (p - 1) // n, p)
    elems = []
    cur = 1
    for _ in range(n):
        elems.append(cur)
        cur = (cur * h) % p
    return elems


def poly_from_roots(roots, p):
    """Monic ``prod_{a in roots} (X - a)`` mod p, low-degree-first coefficients."""
    coeffs = [1]
    for a in roots:
        new = [0] * (len(coeffs) + 1)
        neg_a = (-a) % p
        for i, c in enumerate(coeffs):
            new[i] = (new[i] + c * neg_a) % p
            new[i + 1] = (new[i + 1] + c) % p
        coeffs = new
    return coeffs  # length len(roots)+1, coeffs[-1] == 1 (leading)


def top_sigma_key(coeffs, sigma):
    """Top ``min(sigma, m)`` coefficients (below the monic leading term).

    ``coeffs`` is low-degree-first with ``coeffs[-1] == 1``.  The coefficient of
    ``X^{m-1}`` is ``coeffs[m-1]``, of ``X^{m-2}`` is ``coeffs[m-2]``, ...
    A degree-``m`` monic locator has only ``m`` coefficients below the leading
    term, so for ``sigma >= m`` the key is the full non-leading coefficient
    vector --- which uniquely determines the divisor (every fiber a singleton),
    exactly as in the complement-prefix lemma's ``sigma >= m`` branch.
    """
    m = len(coeffs) - 1
    eff = min(sigma, m)
    return tuple(coeffs[m - 1 - j] for j in range(eff))


# ---------------------------------------------------------------------------
# Coset-union (quotient-periodic) structure.
# ---------------------------------------------------------------------------
def subgroup_of_order(H, p, d):
    """The unique order-``d`` subgroup ``K_d <= H`` (as a frozenset)."""
    return frozenset(x for x in H if pow(x, d, p) == 1)


def is_coset_union(A_set, Kd, p):
    """True iff the root set ``A_set`` is a union of ``K_d``-cosets."""
    for a in A_set:
        for kappa in Kd:
            if (a * kappa) % p not in A_set:
                return False
    return True


def coset_union_image_is_valid(A_set, p, d, n):
    """Check the structural injection X^d -> Y for a K_d-coset-union divisor.

    A K_d-coset-union root set ``A`` maps to ``{ a^d : a in A }`` (each coset
    collapses to a single value), which must be a set of distinct
    ``(n/d)``-th roots of unity of size ``|A|/d``.  Returns (ok, image_size).
    """
    image = {pow(a, d, p) for a in A_set}
    expected = len(A_set) // d
    all_roots_of_unity = all(pow(b, n // d, p) == 1 for b in image)
    return (len(image) == expected and all_roots_of_unity), len(image)


# ---------------------------------------------------------------------------
# Main scan.
# ---------------------------------------------------------------------------
def scan(p, n, k, sigma, max_examples=3):
    """Compute the prefix-fiber histogram and quotient-periodic separation."""
    s = k + sigma
    m = n - s
    if not (0 < s <= n) or m < 0:
        raise ValueError(f"need 0 < k+sigma <= n; got k={k} sigma={sigma} n={n}")

    H = subgroup(p, n)
    Hset = set(H)

    # Subgroups K_d of H with d | n, d > 1; quotient-core-active iff d > sigma.
    divisors = [d for d in range(2, n + 1) if n % d == 0]
    Kd = {d: subgroup_of_order(H, p, d) for d in divisors}

    # Enumerate all degree-m divisors (= m-subsets of H), bucket by top-sigma key.
    buckets = defaultdict(list)  # key -> list of frozenset(A)
    for combo in itertools.combinations(H, m):
        coeffs = poly_from_roots(combo, p)
        key = top_sigma_key(coeffs, sigma)
        buckets[key].append(frozenset(combo))

    total = comb(n, m)
    hist = defaultdict(int)  # fiber size -> number of fibers
    max_fiber = 0
    collisions = []  # nonsingleton fibers (capped sample of members)
    # coset-union accounting per active order
    active_orders = [d for d in divisors if d > sigma]
    cu_total = {d: 0 for d in divisors}          # # divisors that are K_d-coset-unions
    cu_injection_ok = {d: True for d in divisors}  # structural injection holds
    # within-fiber coset-union content for nonsingleton fibers
    nonsingleton_members = 0
    nonsingleton_aperiodic_members = 0  # not coset-union for ANY active order d>sigma

    # Coset-union flags per divisor (computed in the bucket pass below).
    cu_flags = {}  # A(frozenset) -> set of orders d for which A is K_d-coset-union
    for key, members in buckets.items():
        size = len(members)
        hist[size] += 1
        max_fiber = max(max_fiber, size)
        for A in members:
            flags = set()
            for d in divisors:
                if len(A) % d == 0 and is_coset_union(A, Kd[d], p):
                    flags.add(d)
                    cu_total[d] += 1
                    ok, _ = coset_union_image_is_valid(A, p, d, n)
                    if not ok:
                        cu_injection_ok[d] = False
            cu_flags[A] = flags
        if size > 1:
            for A in members:
                nonsingleton_members += 1
                if not any(d in cu_flags[A] for d in active_orders):
                    nonsingleton_aperiodic_members += 1
            if len(collisions) < 64:
                sample = [sorted(A) for A in members[:max_examples]]
                collisions.append({
                    "top_sigma_key": list(key),
                    "fiber_size": size,
                    "members_sample": sample,
                    "active_coset_union_members": sum(
                        1 for A in members if any(d in cu_flags[A] for d in active_orders)
                    ),
                })

    # Lemma check: #{K_d-coset-union degree-m divisors} = binom(n/d, m/d) if d|m else 0.
    cu_predicted = {d: (comb(n // d, m // d) if m % d == 0 else 0) for d in divisors}
    cu_identity_ok = (cu_total == cu_predicted)

    # Corollary check: a quotient-core floor max_c|fiber| >= binom(n/d, m/d) for every
    # active order d > sigma with d | gcd(n, s).  Verify the predicted floor is met.
    g = gcd(n, s)
    quot_floor = max(
        [comb(n // d, m // d) for d in divisors if d > sigma and g % d == 0 and m % d == 0],
        default=0,
    )
    floor_respected = (max_fiber >= quot_floor)

    # --- Exact structured (quotient-periodic) count over active orders d > sigma. ---
    # CU_d = {K_d-coset-union degree-m divisors}, |CU_d| = binom(n/d, m/d).
    # CU_d ∩ CU_e = CU_{lcm(d,e)} (closure under <K_d,K_e> = K_{lcm}), so the union
    # over active orders is exact Mobius inclusion-exclusion over the subgroup lattice.
    def _lcm(a, b):
        return a * b // gcd(a, b)

    def cu_count(e):
        return comb(n // e, m // e) if (n % e == 0 and m % e == 0) else 0

    active_set = sorted(d for d in divisors if d > sigma and m % d == 0)
    structured_direct = sum(
        1 for A in cu_flags if any(d in cu_flags[A] for d in active_set)
    )
    incl = 0
    L = len(active_set)
    for mask in range(1, 1 << L):
        e = 0
        for i in range(L):
            if mask & (1 << i):
                e = active_set[i] if e == 0 else _lcm(e, active_set[i])
        sign = 1 if (bin(mask).count("1") % 2 == 1) else -1
        incl += sign * cu_count(e)
    structured_incl_excl = incl
    structured_count_match = (structured_direct == structured_incl_excl)

    # Dyadic collapse: for n a power of two the active orders are nested (powers of
    # two), so the union is exactly CU_{d_min}, d_min = least active order.
    is_dyadic = (n & (n - 1)) == 0
    d_min = active_set[0] if active_set else None
    dyadic_collapse_ok = (
        (structured_direct == cu_count(d_min)) if (is_dyadic and active_set) else True
    )

    # Max APERIODIC fiber size: largest fiber after removing structured members.
    max_aperiodic_fiber = 0
    for members in buckets.values():
        ap = sum(1 for A in members if not any(d in cu_flags[A] for d in active_set))
        max_aperiodic_fiber = max(max_aperiodic_fiber, ap)
    aperiodic_divisors = total - structured_direct

    # --- Dilation equivariance and the period stabilizer. ---
    # h.A = {h*a} acts on divisors; e_j(h.A) = h^j e_j(A), so the top-sigma key
    # transforms by the star-action  h*(c_1,...,c_sigma) = (h c_1, h^2 c_2, ...).
    def dilate_key(key, h):
        return tuple((pow(h, j + 1, p) * key[j]) % p for j in range(len(key)))

    # (i) key-equivariance on a sample of divisors.
    sample_As = [frozenset(c)
                 for c in itertools.islice(itertools.combinations(H, m), 256)]
    equivariant = True
    for A in sample_As:
        kA = top_sigma_key(poly_from_roots(sorted(A), p), sigma)
        for h in H:
            hA = sorted((h * a) % p for a in A)
            if top_sigma_key(poly_from_roots(hA, p), sigma) != dilate_key(kA, h):
                equivariant = False
                break
        if not equivariant:
            break

    # (ii) dilation stabilizer order == maximal coset-union period, for all A.
    stab_eq_period = True
    for A in cu_flags:
        stab = sum(1 for h in H if frozenset((h * a) % p for a in A) == A)
        period = max(cu_flags[A] | {1})
        if stab != period:
            stab_eq_period = False
            break

    # (iii) fiber sizes are constant on star-orbits of the prefix space.
    sizes = {key: len(members) for key, members in buckets.items()}
    fiber_const_on_orbits = all(
        (dilate_key(key, h) in sizes and sizes[dilate_key(key, h)] == sz)
        for key, sz in sizes.items() for h in H
    )

    # --- Prefix-space localization of the quotient core. ---
    # For A in fiber c: Stab_H(A) ⊆ Stab_star(c) = K_{g_c}, hence per(A) | g_c,
    # where g_c = gcd(n, {j : c_j != 0}) and coordinate j (1-based) carries e_j.
    def g_c_of_key(key):
        g = n
        for j in range(len(key)):
            if key[j] % p != 0:
                g = gcd(g, j + 1)
        return g

    per_divides_gc = True          # Stab_H(A) ⊆ K_{g_c} for every divisor in its fiber
    gc1_fibers_all_aperiodic = True  # g_c = 1  =>  fiber is purely aperiodic
    orbit_size_ok = True           # K_{g_c} orbit of A has size g_c/gcd(g_c,per(A))
    for key, members in buckets.items():
        gc = g_c_of_key(key)
        memberset = set(members)
        Hc = [h for h in H if pow(h, gc, p) == 1] if gc > 1 else [1]
        seen = set()
        for A in members:
            per = max(cu_flags[A] | {1})
            if gc % per != 0:
                per_divides_gc = False
            if gc == 1 and per != 1:
                gc1_fibers_all_aperiodic = False
            if gc > 1 and A not in seen:
                orb = {frozenset((h * a) % p for a in A) for h in Hc}
                seen |= orb
                if len(orb) != gc // gcd(gc, per) or not orb <= memberset:
                    orbit_size_ok = False

    entropy_margin_bits = sigma * _log2(p) - _log2_binom(n, s)
    result = {
        "status": "EXPERIMENTAL/AUDIT",
        "params": {"p": p, "n": n, "k": k, "sigma": sigma, "s": s, "m": m,
                   "rho_num": k, "rho_den": n},
        "total_divisors": total,
        "distinct_prefix_values": len(buckets),
        "fiber_size_histogram": dict(sorted(hist.items())),
        "max_fiber_size": max_fiber,
        "entropy_margin_bits": round(entropy_margin_bits, 6),
        "active_quotient_orders_gt_sigma": active_orders,
        "coset_union_counts_by_order": cu_total,
        "coset_union_predicted_by_order": cu_predicted,
        "coset_union_identity_ok": cu_identity_ok,
        "coset_union_injection_ok_by_order": cu_injection_ok,
        "quotient_core_floor": quot_floor,
        "quotient_core_floor_respected": floor_respected,
        "active_order_set": active_set,
        "structured_count_direct": structured_direct,
        "structured_count_incl_excl": structured_incl_excl,
        "structured_count_match": structured_count_match,
        "dyadic_collapse_d_min": d_min,
        "dyadic_collapse_ok": dyadic_collapse_ok,
        "aperiodic_divisors": aperiodic_divisors,
        "max_aperiodic_fiber_size": max_aperiodic_fiber,
        "random_baseline": total / (p ** sigma),
        "dilation_equivariant": equivariant,
        "stab_equals_period": stab_eq_period,
        "fiber_const_on_dilation_orbits": fiber_const_on_orbits,
        "per_divides_gc": per_divides_gc,
        "gc1_fibers_all_aperiodic": gc1_fibers_all_aperiodic,
        "prefix_orbit_size_ok": orbit_size_ok,
        "nonsingleton_members": nonsingleton_members,
        "nonsingleton_aperiodic_members": nonsingleton_aperiodic_members,
        "nonsingleton_all_aperiodic": (
            nonsingleton_members == nonsingleton_aperiodic_members
        ),
        "collisions_sample": collisions[:16],
    }
    return result


def _log2(x):
    from math import log2
    return log2(x)


def _log2_binom(n, s):
    from math import lgamma, log2
    # log2 of binom(n,s) via lgamma for numerical stability
    val = (lgamma(n + 1) - lgamma(s + 1) - lgamma(n - s + 1))
    return val / 0.6931471805599453  # /ln(2)


# ---------------------------------------------------------------------------
# Non-enumerative path: DP over elements + closed-form structured count.
# ---------------------------------------------------------------------------
def structured_count_formula(n, m, sigma):
    """Closed-form structured (quotient-periodic) count and floor (no enumeration).

    Uses §5: |CU_d| = binom(n/d, m/d), CU_d ∩ CU_e = CU_{lcm(d,e)}, over the
    active orders d > sigma dividing gcd(n, m).  Returns (count, floor, active).
    """
    divisors = [d for d in range(2, n + 1) if n % d == 0]
    active = sorted(d for d in divisors if d > sigma and m % d == 0)

    def cu(e):
        return comb(n // e, m // e) if (n % e == 0 and m % e == 0) else 0

    incl, L = 0, len(active)
    for mask in range(1, 1 << L):
        e = 0
        for i in range(L):
            if mask & (1 << i):
                e = active[i] if e == 0 else e * active[i] // gcd(e, active[i])
        incl += (1 if bin(mask).count("1") % 2 else -1) * cu(e)
    floor = max([cu(d) for d in active], default=0)
    return incl, floor, active


def count_histogram_dp(p, n, k, sigma):
    """Prefix-fiber histogram WITHOUT enumerating divisors.

    DP over the elements of H tracking (chosen size, e_1..e_eff mod p), using the
    elementary-symmetric recurrence e'_i = e_i + h e_{i-1}.  State space is
    (m+1) * p^eff, eff = min(sigma, m), so this reaches n far beyond brute force
    for small sigma.  Returns {key: count} in the same top-sigma-coeff convention
    as ``scan``.
    """
    s = k + sigma
    m = n - s
    eff = min(sigma, m)
    H = subgroup(p, n)
    dp = {(0, (0,) * eff): 1}
    for h in H:
        ndp = defaultdict(int)
        for (size, e), cnt in dp.items():
            ndp[(size, e)] += cnt          # skip h
            if size + 1 <= m:              # include h
                ne = list(e)
                for i in range(eff, 0, -1):
                    e_im1 = e[i - 2] if i - 1 >= 1 else 1
                    ne[i - 1] = (e[i - 1] + h * e_im1) % p
                ndp[(size + 1, tuple(ne))] += cnt
        dp = ndp
    hist = defaultdict(int)
    for (size, e), cnt in dp.items():
        if size == m:
            key = tuple(((-1) ** (j + 1) * e[j]) % p for j in range(eff))
            hist[key] += cnt
    return dict(hist)


def dp_summary(p, n, k, sigma):
    """n-scalable summary: DP histogram + closed-form structured count.

    By §7 the generic prefixes (first coordinate != 0) are purely aperiodic, so
    ``max_generic_fiber`` is the maximal *aperiodic* fiber.
    """
    s, m = k + sigma, n - (k + sigma)
    hist = count_histogram_dp(p, n, k, sigma)
    total = comb(n, m)
    max_fiber = max(hist.values())

    # Honest aperiodic max: by §7 a fiber is purely aperiodic iff g_c = 1, where
    # g_c = gcd(n, {j : c_j != 0}) and coordinate j (1-based) carries e_j.
    def g_c_of_key(key):
        g = n
        for j in range(len(key)):
            if key[j] % p != 0:
                g = gcd(g, j + 1)
        return g

    max_generic = max((v for key, v in hist.items() if g_c_of_key(key) == 1),
                      default=0)
    struct, floor, active = structured_count_formula(n, m, sigma)
    return {
        "params": {"p": p, "n": n, "k": k, "sigma": sigma, "s": s, "m": m},
        "total_divisors": total,
        "distinct_prefixes": len(hist),
        "max_fiber_size": max_fiber,
        "max_generic_aperiodic_fiber": max_generic,
        "structured_count": struct,
        "quotient_core_floor": floor,
        "active_orders": active,
        "random_baseline": total / (p ** sigma),
        "entropy_margin_bits": round(sigma * _log2(p) - _log2_binom(n, s), 4),
        "dp_histogram_sum": sum(hist.values()),
    }


def self_check():
    """Reproduce the F_17 certificate numbers from l1_aperiodic_prefix_collision.md."""
    r = scan(p=17, n=16, k=6, sigma=4)
    expected = {
        "total_divisors": 8008,
        "distinct_prefix_values": 7968,
        "max_fiber_size": 2,
    }
    ok = True
    for key, exp in expected.items():
        got = r[key]
        flag = "OK " if got == exp else "FAIL"
        if got != exp:
            ok = False
        print(f"  [{flag}] {key}: got {got}, expected {exp}")
    two = r["fiber_size_histogram"].get(2, 0)
    flag = "OK " if two == 40 else "FAIL"
    if two != 40:
        ok = False
    print(f"  [{flag}] two_point_fibers: got {two}, expected 40")
    # All 40 nonsingleton fibers must be aperiodic for orders {8, 16} (d > sigma=4).
    flag = "OK " if r["nonsingleton_all_aperiodic"] else "FAIL"
    if not r["nonsingleton_all_aperiodic"]:
        ok = False
    print(f"  [{flag}] all nonsingleton fibers aperiodic for orders {r['active_quotient_orders_gt_sigma']}: "
          f"{r['nonsingleton_all_aperiodic']}")
    # Structural coset-union injection must hold for every order.
    flag = "OK " if all(r["coset_union_injection_ok_by_order"].values()) else "FAIL"
    if not all(r["coset_union_injection_ok_by_order"].values()):
        ok = False
    print(f"  [{flag}] coset-union X^d->Y injection valid for all orders: "
          f"{r['coset_union_injection_ok_by_order']}")
    # Lemma identity and corollary floor over a small parameter sweep.
    sweep = [(17, 16, k, sg) for k in range(2, 9) for sg in range(1, 6)
             if 0 < k + sg <= 15]
    id_ok = floor_ok = struct_ok = collapse_ok = True
    equiv_ok = stab_ok = orbit_ok = True
    gc_ok = gc1_ok = porbit_ok = True
    for (pp, nn, kk, ss) in sweep:
        rr = scan(pp, nn, kk, ss)
        id_ok &= rr["coset_union_identity_ok"]
        floor_ok &= rr["quotient_core_floor_respected"]
        struct_ok &= rr["structured_count_match"]
        collapse_ok &= rr["dyadic_collapse_ok"]
        equiv_ok &= rr["dilation_equivariant"]
        stab_ok &= rr["stab_equals_period"]
        orbit_ok &= rr["fiber_const_on_dilation_orbits"]
        gc_ok &= rr["per_divides_gc"]
        gc1_ok &= rr["gc1_fibers_all_aperiodic"]
        porbit_ok &= rr["prefix_orbit_size_ok"]
    flag = "OK " if id_ok else "FAIL"
    if not id_ok:
        ok = False
    print(f"  [{flag}] coset-union count = binom(n/d,m/d) across {len(sweep)} (k,sigma) cases: {id_ok}")
    flag = "OK " if floor_ok else "FAIL"
    if not floor_ok:
        ok = False
    print(f"  [{flag}] quotient-core floor respected across {len(sweep)} (k,sigma) cases: {floor_ok}")
    flag = "OK " if struct_ok else "FAIL"
    if not struct_ok:
        ok = False
    print(f"  [{flag}] structured count: direct == incl-excl across {len(sweep)} cases: {struct_ok}")
    flag = "OK " if collapse_ok else "FAIL"
    if not collapse_ok:
        ok = False
    print(f"  [{flag}] dyadic collapse to CU_dmin across {len(sweep)} cases: {collapse_ok}")
    flag = "OK " if equiv_ok else "FAIL"
    if not equiv_ok:
        ok = False
    print(f"  [{flag}] dilation key-equivariance across {len(sweep)} cases: {equiv_ok}")
    flag = "OK " if stab_ok else "FAIL"
    if not stab_ok:
        ok = False
    print(f"  [{flag}] dilation stabilizer == coset-union period across {len(sweep)} cases: {stab_ok}")
    flag = "OK " if orbit_ok else "FAIL"
    if not orbit_ok:
        ok = False
    print(f"  [{flag}] fiber sizes constant on dilation orbits across {len(sweep)} cases: {orbit_ok}")
    flag = "OK " if gc_ok else "FAIL"
    if not gc_ok:
        ok = False
    print(f"  [{flag}] per(A) | g_c (quotient core ⊆ symmetric prefixes) across {len(sweep)} cases: {gc_ok}")
    flag = "OK " if gc1_ok else "FAIL"
    if not gc1_ok:
        ok = False
    print(f"  [{flag}] g_c=1 fibers purely aperiodic across {len(sweep)} cases: {gc1_ok}")
    flag = "OK " if porbit_ok else "FAIL"
    if not porbit_ok:
        ok = False
    print(f"  [{flag}] prefix-stabilizer orbit sizes g_c/gcd(g_c,per) across {len(sweep)} cases: {porbit_ok}")
    # Non-enumerative DP counter must reproduce the brute-force size distribution.
    from collections import Counter
    dp_ok = True
    for (kk, ss) in [(6, 4), (4, 4), (6, 2), (7, 1), (5, 3)]:
        size_dist_dp = dict(Counter(count_histogram_dp(17, 16, kk, ss).values()))
        size_dist_brute = scan(17, 16, kk, ss)["fiber_size_histogram"]
        if size_dist_dp != size_dist_brute:
            dp_ok = False
    flag = "OK " if dp_ok else "FAIL"
    if not dp_ok:
        ok = False
    print(f"  [{flag}] DP counter == brute-force size distribution (5 cases): {dp_ok}")
    # Closed-form structured count must match the enumerated one.
    sf_ok = True
    for (pp, nn, kk, ss) in sweep:
        r2 = scan(pp, nn, kk, ss)
        sc, fl, _ = structured_count_formula(nn, nn - kk - ss, ss)
        if sc != r2["structured_count_direct"] or fl != r2["quotient_core_floor"]:
            sf_ok = False
    flag = "OK " if sf_ok else "FAIL"
    if not sf_ok:
        ok = False
    print(f"  [{flag}] closed-form structured count == enumerated across {len(sweep)} cases: {sf_ok}")
    return ok


def human_table(r):
    p = r["params"]
    lines = []
    lines.append(f"L1 prefix-fiber divisor-coefficient scan  (status {r['status']})")
    lines.append(f"  F_{p['p']}, n={p['n']}, k={p['k']}, sigma={p['sigma']}, "
                 f"s={p['s']}, m={p['m']}  (rho={p['rho_num']}/{p['rho_den']})")
    lines.append(f"  degree-m divisors of X^n-1 : {r['total_divisors']}")
    lines.append(f"  distinct top-sigma prefixes: {r['distinct_prefix_values']}")
    lines.append(f"  fiber-size histogram       : {r['fiber_size_histogram']}")
    lines.append(f"  max fiber size             : {r['max_fiber_size']}")
    lines.append(f"  entropy margin (bits)      : {r['entropy_margin_bits']}")
    lines.append(f"  quotient orders d>sigma    : {r['active_quotient_orders_gt_sigma']}")
    lines.append(f"  coset-union divisors / ord : {r['coset_union_counts_by_order']}")
    lines.append(f"  ... predicted binom(n/d,m/d): {r['coset_union_predicted_by_order']}  "
                 f"(identity ok: {r['coset_union_identity_ok']})")
    lines.append(f"  X^d->Y injection ok / ord  : {r['coset_union_injection_ok_by_order']}")
    lines.append(f"  quotient-core floor        : {r['quotient_core_floor']}  "
                 f"(respected: {r['quotient_core_floor_respected']})")
    lines.append(f"  active orders (d>sigma)    : {r['active_order_set']}")
    lines.append(f"  structured count (direct)  : {r['structured_count_direct']}  "
                 f"(incl-excl: {r['structured_count_incl_excl']}, "
                 f"match: {r['structured_count_match']})")
    lines.append(f"  dyadic collapse d_min      : {r['dyadic_collapse_d_min']}  "
                 f"(ok: {r['dyadic_collapse_ok']})")
    lines.append(f"  aperiodic divisors         : {r['aperiodic_divisors']}  "
                 f"(max aperiodic fiber: {r['max_aperiodic_fiber_size']})")
    lines.append(f"  random baseline binom/q^s  : {r['random_baseline']:.4f}")
    lines.append(f"  dilation-equivariant keys  : {r['dilation_equivariant']}")
    lines.append(f"  stab order == period       : {r['stab_equals_period']}")
    lines.append(f"  fiber const on dil. orbits : {r['fiber_const_on_dilation_orbits']}")
    lines.append(f"  per(A) | g_c (all fibers)  : {r['per_divides_gc']}")
    lines.append(f"  g_c=1 fibers all aperiodic : {r['gc1_fibers_all_aperiodic']}")
    lines.append(f"  prefix-stab orbit sizes ok : {r['prefix_orbit_size_ok']}")
    lines.append(f"  nonsingleton members       : {r['nonsingleton_members']}")
    lines.append(f"  ... of which aperiodic     : {r['nonsingleton_aperiodic_members']}")
    lines.append(f"  all nonsingleton aperiodic : {r['nonsingleton_all_aperiodic']}")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--p", type=int, default=17, help="prime field size (n | p-1)")
    ap.add_argument("--n", type=int, default=16, help="subgroup order")
    ap.add_argument("--k", type=int, default=6, help="RS dimension")
    ap.add_argument("--sigma", type=int, default=4, help="prefix length / slack")
    ap.add_argument("--format", choices=["human", "json"], default="human")
    ap.add_argument("--self-check", action="store_true",
                    help="reproduce the F_17 certificate from the L1 aperiodic note")
    ap.add_argument("--dp-summary", action="store_true",
                    help="non-enumerative DP summary (scales past brute force)")
    args = ap.parse_args(argv)

    if args.dp_summary:
        r = dp_summary(args.p, args.n, args.k, args.sigma)
        if args.format == "json":
            print(json.dumps(r, indent=2, default=list))
        else:
            pr = r["params"]
            print(f"DP prefix-fiber summary  F_{pr['p']}, n={pr['n']}, k={pr['k']}, "
                  f"sigma={pr['sigma']}, s={pr['s']}, m={pr['m']}")
            print(f"  total divisors             : {r['total_divisors']}")
            print(f"  distinct prefixes          : {r['distinct_prefixes']}")
            print(f"  max fiber size             : {r['max_fiber_size']}")
            print(f"  max GENERIC aperiodic fiber: {r['max_generic_aperiodic_fiber']}")
            print(f"  structured count (formula) : {r['structured_count']}")
            print(f"  quotient-core floor        : {r['quotient_core_floor']}  "
                  f"(active orders {r['active_orders']})")
            print(f"  random baseline binom/q^s  : {r['random_baseline']:.4f}")
            print(f"  entropy margin (bits)      : {r['entropy_margin_bits']}")
            print(f"  DP histogram sum == total  : {r['dp_histogram_sum'] == r['total_divisors']}")
        return 0

    if args.self_check:
        print("Self-check against l1_aperiodic_prefix_collision.md (F_17, k=6, sigma=4):")
        ok = self_check()
        print("RESULT:", "PASS" if ok else "FAIL")
        return 0 if ok else 1

    r = scan(args.p, args.n, args.k, args.sigma)
    if args.format == "json":
        print(json.dumps(r, indent=2, default=list))
    else:
        print(human_table(r))
    return 0


if __name__ == "__main__":
    sys.exit(main())
