import M31SelectorSpectrum.Atlas

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

/-!
# Structural generator for the M31 depth-32 selector spectrum

The exhaustive atlas computation in `M31SelectorSpectrum.Atlas` scans 68,896
nontrivial compressed collision edges.  This module proves that its rooted
maximum spectrum is produced by a much smaller law:

* the zero-relation central pattern contributes the even-shell term
  `C(7,t/2)^2`; and
* four cross-pattern signatures generate the only odd-shell maxima needed in
  the final envelope.

For a signature `(a,b,c,f,d)`, `crossSignatureCount` is the coefficient law

`[z^d q^(t-f)] (q+z)^a (q^2+z)^b (1+z)^c`.

The four signatures are extracted from four explicit compressed edges in the
frozen selector atlas.  Thus the generator is not a numerical fit to the
fourteen output values.

The module is finite and support-selector level only.  It proves no universal
transport from deployed supports to the selector atlas and no off-remainder,
received-word, codeword, ray, slope, or list-row claim.
-/

namespace M31SelectorSpectrum.SpectrumGenerator

private def choose (n k : Nat) : Nat :=
  M31SelectorSpectrum.Atlas.fastBinomial n k

/--
A compressed cross-pattern signature.

* `anchorOne`: partner-zero coordinates where the anchor selects one block;
* `anchorBoth`: partner-zero coordinates where the anchor selects both blocks;
* `zeroZero`: partner-zero coordinates where the anchor selects neither block;
* `fixedRemoved`: deficiency already forced outside those coordinates; and
* `partnerDoubled`: zero-pairs doubled by the partner selector.
-/
structure CrossSignature where
  anchorOne : Nat
  anchorBoth : Nat
  zeroZero : Nat
  fixedRemoved : Nat
  partnerDoubled : Nat
  deriving Repr, BEq, DecidableEq

/--
Rooted count generated by one cross-pattern signature at block deficiency `t`.
This is the binomial expansion of
`[z^d q^(t-f)] (q+z)^a (q^2+z)^b (1+z)^c`.
-/
def crossSignatureCount
    (signature : CrossSignature) (blockDeficiency : Nat) : Nat :=
  (List.range (signature.anchorOne + 1)).foldl (fun total x =>
    (List.range (signature.anchorBoth + 1)).foldl (fun subtotal y =>
      if x + y ≤ signature.partnerDoubled then
        let z := signature.partnerDoubled - x - y
        if z ≤ signature.zeroZero then
          let removed := signature.fixedRemoved +
            (signature.anchorOne - x) +
            2 * (signature.anchorBoth - y)
          if removed = blockDeficiency then
            subtotal +
              choose signature.anchorOne x *
              choose signature.anchorBoth y *
              choose signature.zeroZero z
          else
            subtotal
        else
          subtotal
      else
        subtotal) total) 0

/-- The zero-relation central-pattern contribution. -/
def centralPatternCount (blockDeficiency : Nat) : Nat :=
  if blockDeficiency % 2 = 1 then
    0
  else
    let movedPairs := blockDeficiency / 2
    choose 7 movedPairs * choose 7 movedPairs

/-- Maximizer for the first nonzero odd shell, `t=7` (`e=224`). -/
def oddSevenSignature : CrossSignature :=
  { anchorOne := 5
  , anchorBoth := 0
  , zeroZero := 6
  , fixedRemoved := 4
  , partnerDoubled := 3 }

/-- Maximizer for `t=9` (`e=288`). -/
def oddNineSignature : CrossSignature :=
  { anchorOne := 8
  , anchorBoth := 0
  , zeroZero := 3
  , fixedRemoved := 5
  , partnerDoubled := 5 }

/-- Maximizer for `t=11` (`e=352`). -/
def oddElevenSignature : CrossSignature :=
  { anchorOne := 5
  , anchorBoth := 3
  , zeroZero := 3
  , fixedRemoved := 3
  , partnerDoubled := 5 }

/-- Maximizer for `t=13` (`e=416`). -/
def oddThirteenSignature : CrossSignature :=
  { anchorOne := 3
  , anchorBoth := 2
  , zeroZero := 3
  , fixedRemoved := 7
  , partnerDoubled := 4 }

/-- The four cross-pattern signatures retained by the structural envelope. -/
def exceptionalSignatures : List CrossSignature :=
  [ oddSevenSignature
  , oddNineSignature
  , oddElevenSignature
  , oddThirteenSignature ]

/-- Maximum contribution of a supplied signature list. -/
def signatureEnvelope
    (signatures : List CrossSignature) (blockDeficiency : Nat) : Nat :=
  signatures.foldl (fun best signature =>
    max best (crossSignatureCount signature blockDeficiency)) 0

/-- The cross-pattern part of the structural generator. -/
def exceptionalEnvelope (blockDeficiency : Nat) : Nat :=
  signatureEnvelope exceptionalSignatures blockDeficiency

/--
Structural generator for the complete rooted selector maximum at block
deficiency `t`.
-/
def selectorSpectrumGenerator (blockDeficiency : Nat) : Nat :=
  max (centralPatternCount blockDeficiency)
    (exceptionalEnvelope blockDeficiency)

/-- Generated spectrum for `t=1,...,14`. -/
def generatedBlockDeficiencySpectrum : List Nat :=
  (List.range 14).map fun index => selectorSpectrumGenerator (index + 1)

/-- The central binomial law on the fourteen relevant shells. -/
def expectedCentralSpectrum : List Nat :=
  [0, 49, 0, 441, 0, 1225, 0, 1225, 0, 441, 0, 49, 0, 1]

/-- The four-signature cross-pattern envelope on the same shells. -/
def expectedExceptionalEnvelopeSpectrum : List Nat :=
  [0, 0, 0, 0, 0, 10, 60, 108, 210, 168, 45, 11, 3, 0]

/-! ## Explicit source edges for the four exceptional signatures -/

abbrev Pattern := List Int

private def pairPart (pattern : Pattern) : List Int := pattern.take 14
private def singletonPart (pattern : Pattern) : List Int :=
  (pattern.drop 14).take 2

private def zeroPairCount (pattern : Pattern) : Nat :=
  ((pairPart pattern).filter fun state => state == 0).length

private def nonzeroPairCount (pattern : Pattern) : Nat :=
  ((pairPart pattern).filter fun state => !(state == 0)).length

private def singletonOneCount (pattern : Pattern) : Nat :=
  ((singletonPart pattern).filter fun state => state == 1).length

private def baseSelectorSize (pattern : Pattern) : Nat :=
  nonzeroPairCount pattern + singletonOneCount pattern

private def doubledPairCount?
    (pattern : Pattern) (selectorSize : Nat) : Option Nat :=
  let base := baseSelectorSize pattern
  if selectorSize < base then
    none
  else
    let remainder := selectorSize - base
    if remainder % 2 = 1 then
      none
    else
      let doubled := remainder / 2
      if doubled ≤ zeroPairCount pattern then some doubled else none

private def pairRows (left right : Pattern) : List (Int × Int) :=
  List.zip (pairPart left) (pairPart right)

private def countPairRows
    (left right : Pattern) (predicate : Int → Int → Bool) : Nat :=
  ((pairRows left right).filter fun row => predicate row.1 row.2).length

private def zeroZeroCount (left right : Pattern) : Nat :=
  countPairRows left right fun a b => (a == 0) && (b == 0)

private def zeroNonzeroCount (left right : Pattern) : Nat :=
  countPairRows left right fun a b => (a == 0) && !(b == 0)

private def nonzeroZeroCount (left right : Pattern) : Nat :=
  countPairRows left right fun a b => !(a == 0) && (b == 0)

private def oppositeNonzeroCount (left right : Pattern) : Nat :=
  countPairRows left right fun a b =>
    !(a == 0) && !(b == 0) && !(a == b)

private def singletonRemovedCount (left right : Pattern) : Nat :=
  ((List.zip (singletonPart left) (singletonPart right)).filter fun row =>
    (row.1 == 1) && (row.2 == 0)).length

/--
Extract the five count parameters used by the coefficient law from one oriented
compressed edge, one selector size, and the number of anchor-doubled zero-zero
coordinates.
-/
def signatureFromSource
    (anchor partner : Pattern) (selectorSize anchorBoth : Nat) : CrossSignature :=
  let anchorDoubled := (doubledPairCount? anchor selectorSize).getD 0
  let partnerDoubled := (doubledPairCount? partner selectorSize).getD 0
  let n00 := zeroZeroCount anchor partner
  let anchorOnlyDoubled := anchorDoubled - anchorBoth
  { anchorOne := nonzeroZeroCount anchor partner
  , anchorBoth := anchorBoth
  , zeroZero := n00 - anchorBoth
  , fixedRemoved := oppositeNonzeroCount anchor partner +
      anchorOnlyDoubled + singletonRemovedCount anchor partner
  , partnerDoubled := partnerDoubled }

/-- Oriented source for the value 60 at block deficiency seven. -/
def oddSevenAnchor : Pattern :=
  [-1, 0, 0, 0, 1, 0, 0, 1, -1, 0, 1, -1, -1, -1, 0, 1]

def oddSevenPartner : Pattern :=
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]

/-- Oriented source for the value 210 at block deficiency nine. -/
def oddNineAnchor : Pattern :=
  [1, 1, 1, 0, 1, 1, -1, -1, 1, -1, -1, 0, 0, -1, 1, 1]

def oddNinePartner : Pattern :=
  [0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 1, 0, 0]

/-- Oriented source for the value 45 at block deficiency eleven. -/
def oddElevenAnchor : Pattern :=
  [1, 0, 0, 0, -1, 0, 0, -1, 1, 0, -1, 1, 1, 1, 0, 0]

def oddElevenPartner : Pattern :=
  [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, -1, 0, 1]

/-- Oriented source for the value 3 at block deficiency thirteen. -/
def oddThirteenAnchor : Pattern :=
  [1, -1, 0, -1, 1, 0, 0, -1, 0, 1, 1, 0, -1, 1, 0, 1]

def oddThirteenPartner : Pattern :=
  [-1, 0, 0, 1, 0, 0, 0, 1, 0, 0, -1, 0, 1, -1, 0, 0]

/--
The four sources are actual edges in the frozen 68,896-edge atlas.  The final
three happen to be stored in the opposite canonical orientation; the exhaustive
atlas computation scans both orientations.
-/
theorem exceptional_sources_are_atlas_edges :
    M31SelectorSpectrum.Atlas.allPatternPairs.contains
      (oddSevenAnchor, oddSevenPartner) = true ∧
    M31SelectorSpectrum.Atlas.allPatternPairs.contains
      (oddNinePartner, oddNineAnchor) = true ∧
    M31SelectorSpectrum.Atlas.allPatternPairs.contains
      (oddElevenPartner, oddElevenAnchor) = true ∧
    M31SelectorSpectrum.Atlas.allPatternPairs.contains
      (oddThirteenPartner, oddThirteenAnchor) = true := by
  native_decide

/-- Exact extraction of the four retained signatures from their atlas edges. -/
theorem exceptional_sources_extract_signatures :
    signatureFromSource oddSevenAnchor oddSevenPartner 9 0 =
      oddSevenSignature ∧
    signatureFromSource oddNineAnchor oddNinePartner 13 0 =
      oddNineSignature ∧
    signatureFromSource oddElevenAnchor oddElevenPartner 14 3 =
      oddElevenSignature ∧
    signatureFromSource oddThirteenAnchor oddThirteenPartner 14 2 =
      oddThirteenSignature := by
  native_decide

/-! ## Closed spectrum claims -/

/-- Each retained signature attains its claimed odd-shell maximum. -/
theorem exceptional_signature_values :
    crossSignatureCount oddSevenSignature 7 = 60 ∧
    crossSignatureCount oddNineSignature 9 = 210 ∧
    crossSignatureCount oddElevenSignature 11 = 45 ∧
    crossSignatureCount oddThirteenSignature 13 = 3 := by
  native_decide

/-- Exact central-pattern spectrum generated by `C(7,t/2)^2`. -/
theorem central_pattern_spectrum_exact :
    (List.range 14).map (fun index => centralPatternCount (index + 1)) =
      expectedCentralSpectrum := by
  native_decide

/-- Exact envelope generated by the four cross-pattern signatures. -/
theorem exceptional_envelope_spectrum_exact :
    (List.range 14).map (fun index => exceptionalEnvelope (index + 1)) =
      expectedExceptionalEnvelopeSpectrum := by
  native_decide

/--
The compact structural generator agrees directly with the exhaustive 68,896-edge
selector-atlas maximum on every relevant block deficiency.
-/
theorem structural_generator_matches_exhaustive_selector_atlas :
    generatedBlockDeficiencySpectrum =
      M31SelectorSpectrum.Atlas.computedBlockDeficiencySpectrum := by
  native_decide

/-- The structural law prints the atlas spectrum exactly. -/
theorem structural_generator_prints_atlas_spectrum :
    generatedBlockDeficiencySpectrum =
      M31SelectorSpectrum.Atlas.expectedBlockDeficiencySpectrum := by
  native_decide

/--
The four exceptional signatures are irredundant for this generator: deleting
one lowers the corresponding odd-shell value from `60,210,45,3` to
`45,136,28,0`, respectively.
-/
theorem exceptional_signatures_irredundant :
    max (centralPatternCount 7)
      (signatureEnvelope
        [oddNineSignature, oddElevenSignature, oddThirteenSignature] 7) = 45 ∧
    max (centralPatternCount 9)
      (signatureEnvelope
        [oddSevenSignature, oddElevenSignature, oddThirteenSignature] 9) = 136 ∧
    max (centralPatternCount 11)
      (signatureEnvelope
        [oddSevenSignature, oddNineSignature, oddThirteenSignature] 11) = 28 ∧
    max (centralPatternCount 13)
      (signatureEnvelope
        [oddSevenSignature, oddNineSignature, oddElevenSignature] 13) = 0 := by
  native_decide

#print axioms exceptional_sources_are_atlas_edges
#print axioms exceptional_sources_extract_signatures
#print axioms exceptional_signature_values
#print axioms central_pattern_spectrum_exact
#print axioms exceptional_envelope_spectrum_exact
#print axioms structural_generator_matches_exhaustive_selector_atlas
#print axioms structural_generator_prints_atlas_spectrum
#print axioms exceptional_signatures_irredundant

end M31SelectorSpectrum.SpectrumGenerator
