#!/usr/bin/env python3
"""Verify subgroup syndrome realizability for synthetic M3 inputs."""

from __future__ import annotations

import argparse
import json
from hashlib import sha256
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from experimental.scripts.emit_f17_32_hankel_row_descriptor import (  # noqa: E402
    Field,
    K,
    MODULUS,
    N,
    P,
    hash_json,
)


SCHEMA_VERSION = "f17-32-m3-syndrome-realizability-v1"
Q_LINE = 17**32
R = N - K
ROW_DESCRIPTOR_REF = (
    "experimental/data/certificates/hankel-f17-32-row-descriptor/"
    "f17_32_n512_k256_hankel_row_descriptor.json"
)
SUBGROUP_SECTION_REF = (
    "experimental/data/certificates/subgroup-syndrome-section/"
    "subgroup_syndrome_section_certificate.json"
)
SOURCES = [
    {
        "packet_id": "rank_witness_a385",
        "input_ref": (
            "experimental/data/hankel-regular-minor-inputs/"
            "f17_32_n512_k256_a385_rank_witness_input.json"
        ),
    },
    {
        "packet_id": "rank_witness_a426",
        "input_ref": (
            "experimental/data/hankel-regular-minor-inputs/"
            "f17_32_n512_k256_a426_rank_witness_input.json"
        ),
    },
    {
        "packet_id": "fixed_top_window_a421_426",
        "input_ref": (
            "experimental/data/hankel-regular-minor-inputs/"
            "f17_32_n512_k256_a421_426_fixed_prefix92_input.json"
        ),
    },
    {
        "packet_id": "contiguous_gcd_a426",
        "input_ref": (
            "experimental/data/hankel-regular-minor-inputs/"
            "f17_32_n512_k256_a426_contiguous_gcd4_input.json"
        ),
    },
]


def load_json(ref: str | Path) -> dict[str, Any]:
    path = ref if isinstance(ref, Path) else ROOT / ref
    return json.loads(path.read_text(encoding="utf-8"))


def sha256_file(ref: str) -> str:
    return sha256((ROOT / ref).read_bytes()).hexdigest()


def hash_value(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return sha256(payload).hexdigest()


def render(value: dict[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def validate_subgroup(row_descriptor: dict[str, Any], field: Field) -> dict[str, Any]:
    domain_encodings = row_descriptor["domain"]["domain_encodings"]
    generator = field.decode(row_descriptor["domain"]["generator_encoding"])
    require(len(domain_encodings) == N, "domain length mismatch")
    require(
        hash_json(domain_encodings) == row_descriptor["row"]["domain_hash"],
        "domain hash mismatch",
    )
    require(field.pow(generator, N) == field.one, "generator does not close at order 512")
    require(
        field.pow(generator, N // 2) != field.one,
        "generator has smaller order dividing 256",
    )

    current = field.one
    replayed_domain = []
    for _ in range(N):
        replayed_domain.append(field.encode(current))
        current = field.mul(current, generator)
    require(replayed_domain == domain_encodings, "domain is not the listed generator orbit")
    require(current == field.one, "generator orbit does not close")

    positive_nonfixed = 0
    negative_nonfixed = 0
    for exponent in range(1, R):
        require(
            field.pow(generator, exponent) != field.one,
            f"positive exponent {exponent} fixes the subgroup character",
        )
        require(
            field.pow(generator, N - exponent) != field.one,
            f"negative exponent -{exponent} fixes the subgroup character",
        )
        positive_nonfixed += 1
        negative_nonfixed += 1

    return {
        "domain_replayed_from_generator": True,
        "generator_order": N,
        "checked_exponent_range": f"{-(R - 1)}..{R - 1}",
        "positive_nonzero_exponents_checked": positive_nonfixed,
        "negative_nonzero_exponents_checked": negative_nonfixed,
        "zero_exponent_sum": N,
        "zero_exponent_sum_mod_17": N % P,
        "character_orthogonality": (
            "sum_{x in H} x^e is 512 for e=0 and 0 for "
            "0<|e|<256, because H is generated by an exact order-512 element"
        ),
    }


def validate_source(source: dict[str, str], row_descriptor: dict[str, Any]) -> dict[str, Any]:
    input_data = load_json(source["input_ref"])
    row = input_data["row"]
    require(row["n"] == N, f"{source['packet_id']}: n mismatch")
    require(row["k"] == K, f"{source['packet_id']}: k mismatch")
    require(row["field"] == "F_17^32", f"{source['packet_id']}: field mismatch")
    require(
        row["domain_hash"] == row_descriptor["row"]["domain_hash"],
        f"{source['packet_id']}: domain hash mismatch",
    )
    require(
        input_data["line_syndrome"]["length"] == R,
        f"{source['packet_id']}: syndrome length mismatch",
    )
    require(
        input_data["sampler"] == "finite_affine_line",
        f"{source['packet_id']}: sampler mismatch",
    )

    components = []
    for label in ("u", "v"):
        encoded_syndrome = input_data["line_syndrome"][label]
        require(
            len(encoded_syndrome) == R,
            f"{source['packet_id']}:{label}: syndrome coordinate length mismatch",
        )
        components.append(
            {
                "component": label,
                "syndrome_hash": hash_value(encoded_syndrome),
                "syndrome_nonzero_count": sum(1 for value in encoded_syndrome if value),
                "realized_by_section": True,
                "line_value_coordinates": N,
            }
        )

    return {
        "packet_id": source["packet_id"],
        "input_ref": source["input_ref"],
        "input_sha256": sha256_file(source["input_ref"]),
        "exact_agreements": input_data["exact_agreements"],
        "witness_node_prefix_count": input_data["line_syndrome"][
            "witness_node_prefix_count"
        ],
        "components": components,
    }


def build_certificate() -> dict[str, Any]:
    field = Field(P, MODULUS)
    row_descriptor = load_json(ROW_DESCRIPTOR_REF)
    subgroup_section = load_json(SUBGROUP_SECTION_REF)
    require(row_descriptor["row"]["n"] == N, "row descriptor n mismatch")
    require(row_descriptor["row"]["k"] == K, "row descriptor k mismatch")
    require(row_descriptor["row"]["field"] == "F_17^32", "row descriptor field mismatch")
    require(row_descriptor["row"]["field_order"] == Q_LINE, "row descriptor order mismatch")
    require(row_descriptor["row"]["syndrome_length"] == R, "row descriptor syndrome mismatch")
    require(
        subgroup_section["schema_version"] == "f17-32-m3-subgroup-syndrome-section-v1",
        "unexpected subgroup-section schema",
    )
    require(
        subgroup_section["row"]["domain_hash"] == row_descriptor["row"]["domain_hash"],
        "section domain mismatch",
    )
    require(subgroup_section["row"]["syndrome_length"] == R, "section syndrome length mismatch")
    require(
        subgroup_section["summary"]["all_basis_coordinates_checked"] == R * R,
        "section basis replay mismatch",
    )

    subgroup_audit = validate_subgroup(row_descriptor, field)
    input_records = [validate_source(source, row_descriptor) for source in SOURCES]
    return {
        "schema_version": SCHEMA_VERSION,
        "status": "PROVED / AUDIT for the listed synthetic syndrome inputs",
        "object": "explicit subgroup line-value section for M3 rank-witness inputs",
        "row": {
            "code": "RS[F_17^32,H,256]",
            "n": N,
            "k": K,
            "field": "F_17^32",
            "q_line": Q_LINE,
            "domain_hash": row_descriptor["row"]["domain_hash"],
            "syndrome_length": R,
        },
        "source_artifacts": {
            "row_descriptor": {
                "ref": ROW_DESCRIPTOR_REF,
                "sha256": sha256_file(ROW_DESCRIPTOR_REF),
            },
            "subgroup_syndrome_section": {
                "ref": SUBGROUP_SECTION_REF,
                "sha256": sha256_file(SUBGROUP_SECTION_REF),
            }
        },
        "subgroup_audit": subgroup_audit,
        "section_formula": {
            "domain": "multiplicative subgroup H of order 512",
            "weighted_syndrome": "s_m=(1/512) sum_{x in H} x*y(x)*x^m",
            "section": "y_s(x)=sum_{a=0}^{255} s_a x^(-a-1)",
            "general_section_ref": SUBGROUP_SECTION_REF,
            "proof": (
                "Substituting the section gives (1/512) sum_a s_a "
                "sum_{x in H} x^(m-a), which equals s_m by the audited "
                "character orthogonality for 0<=a,m<256."
            ),
        },
        "input_records": input_records,
        "summary": {
            "inputs_checked": len(input_records),
            "components_realized": sum(
                len(record["components"]) for record in input_records
            ),
            "syndrome_coordinates_per_component": R,
            "line_value_coordinates_per_component": N,
        },
        "nonclaims": [
            "does not classify arbitrary M3 regular roots",
            "does not prove a worst-case support-wise MCA bound",
            "does not perform tangent, quotient, or extension subtraction",
            "does not replace the remaining universal M3 syndrome-pencil classification",
        ],
    }


def check_certificate(path: Path) -> None:
    expected = render(build_certificate())
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        raise AssertionError(f"syndrome-realizability certificate mismatch: {path}")


def print_summary(certificate: dict[str, Any]) -> None:
    summary = certificate["summary"]
    print("F_17^32 M3 syndrome-realizability certificate")
    print(
        (
            "inputs={inputs_checked}, components={components_realized}, "
            "syndrome coordinates={syndrome_coordinates_per_component}"
        ).format(
            **summary
        )
    )
    print(
        "subgroup audit: {checked_exponent_range}, generator order {generator_order}".format(
            **certificate["subgroup_audit"]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", type=Path)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()

    certificate = build_certificate()
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(render(certificate), encoding="utf-8")
    if args.check:
        check_certificate(args.check)
    print_summary(certificate)


if __name__ == "__main__":
    main()
